# Generated by Django 2.2.11 on 2020-10-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201005_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
